import{a as y,s as h,i as c}from"./assets/vendor-33018bce.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const g=function(o){return o.map(({views:t,comments:r,downloads:n,likes:e,webformatURL:s,tags:i,largeImageURL:f})=>`<li>
        <div class="img-box">
        <a href="${f}">
        <img class="img" src="${s}" alt="${i}" width="360" height="200">
        </a>
        <ul class="value-list">
        <li class="likes value-item"><p class="article">Likes</p><p class="value">${e}</p></li>
        <li class="views value-item" ><p class="article">Views</p><p class="value">${t}</p></li>
        <li class="comments value-item"><p class="article">Comments</p><p class="value">${r}</p></li>
        <li class="downloads value-item"><p class="article">Downloads</p><p class="value">${n}</p></li>
        </ul></div>
        </li>`).join("")},b="https://pixabay.com/api/",v="43211197-e02e136a3ee46bcda7d5bf66f";async function p(o,t=1){const{data:r}=await y(`${b}`,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return r}const d=document.querySelector(".search-form"),L=document.querySelector("input"),C=document.querySelector(".object-list"),a=document.querySelector(".loader-box"),u=document.querySelector(".load-more-btn"),w=new h(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250,showCounter:!1});let l=1;d.addEventListener("submit",$);u.addEventListener("click",x);function $(o){if(o.preventDefault(),!L.value)return c.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",closeOnClick:!0,position:"topCenter"});a.style.display="flex";const t=o.currentTarget.elements.search.value.trim();p(t,l).then(r=>{if(!r.total)return a.style.display="none",c.info({message:"Don't found",closeOnClick:!0,position:"topCenter"});m(r.hits),d.reset(),l*15<=r.totalHits&&(u.style.display="flex"),a.style.display="none"}).catch(r=>(a.style.display="none",c.error({message:`${r.message}`,backgroundColor:"red",position:"topCenter"})))}async function x(o){a.style.display="flex",l++,u.disabled=!0;try{const t=await p(l);m(t.hits),a.style.display="none",l*15>t.totalHits&&(u.style.display="none")}catch(t){return a.style.display="none",c.error({message:`${t.message}`,backgroundColor:"red",position:"topCenter"})}}function m(o){C.insertAdjacentHTML("beforeend",g(o)),w.refresh()}
//# sourceMappingURL=commonHelpers.js.map
